# permissions for end users to edit estorders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: estorder-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: est-operator
    app.kubernetes.io/part-of: est-operator
    app.kubernetes.io/managed-by: kustomize
  name: estorder-editor-role
rules:
- apiGroups:
  - certmanager.jquad.rocks
  resources:
  - estorders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmanager.jquad.rocks
  resources:
  - estorders/status
  verbs:
  - get
