---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - certmanager.jquad.rocks
  resources:
  - clusterestissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmanager.jquad.rocks
  resources:
  - clusterestissuers/finalizers
  verbs:
  - update
- apiGroups:
  - certmanager.jquad.rocks
  resources:
  - clusterestissuers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - certmanager.jquad.rocks
  resources:
  - estissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmanager.jquad.rocks
  resources:
  - estissuers/finalizers
  verbs:
  - update
- apiGroups:
  - certmanager.jquad.rocks
  resources:
  - estissuers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - certmanager.jquad.rocks
  resources:
  - estorders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmanager.jquad.rocks
  resources:
  - estorders/finalizers
  verbs:
  - update
- apiGroups:
  - certmanager.jquad.rocks
  resources:
  - estorders/status
  verbs:
  - get
  - patch
  - update
