apiVersion: certmanager.jquad.rocks/v1
kind: ClusterEstIssuer
metadata:
  labels:
    app.kubernetes.io/name: est-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterestissuer-sample
spec:
  # TODO(user): Add fields here
